version: '3.7'

services:
  front:
    image: basic-front
    build:
      context: ./front
    restart: always
    depends_on:
      - api
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_SSL_CERTIFICATE: /etc/nginx/certs/basic.pem
      NGINX_SSL_CERTIFICATE_KEY: /etc/nginx/certs/basic.key
      API_ROOT_URL: https://localhost:5001
    volumes:
      - ./.keys/basic.pem:/etc/nginx/certs/basic.pem:ro
      - ./.keys/basic.key:/etc/nginx/certs/basic.key:ro
    ports:
      - 5000:443

  api:
    image: basic-api
    build:
      context: ./src
      dockerfile: ./Basic.WebApi/Dockerfile
    restart: always
    depends_on:
      - mysql
      - mssql
    env_file:
      - .env.docker-compose.local
    environment:
      BASEURL: https://localhost:5001
      CORS__ORIGINS: https://localhost:5000
    volumes:
      - ./.keys/basic.pfx:/src/basic.pfx:ro
    ports:
      - 5001:443

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: basic
      MYSQL_USER: basic
      MYSQL_PASSWORD: basic
    volumes:
      - ./support/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    ports:
      - 3306:3306

  mssql:
    image: superfaz/mssql-initialized
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_DATABASE: basic
      MSSQL_USER: basic
      MSSQL_PASSWORD: basic@Passw0rd
    volumes:
      - ./support/mssql-init-sa.sql:/usr/config/init-sa.sql:ro
    ports:
      - 1433:1433

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - mysql
      - mssql
    ports:
      - 8080:8080

  smtp:
    image: maildev/maildev:latest
    restart: always
    ports:
      - 1080:1080
      - 1025:1025

  ldap:
    image: dwimberger/ldap-ad-it:latest
    restart: always
    volumes:
      - ./support/ldap.ldif:/ldap/users.ldif:ro
    ports:
      - 10389:10389
