version: '3.7'

services:
  front:
    image: basic-front
    build:
      context: ./front
      args:
        REACT_APP_API_ROOT_URL: https://localhost:5001
    restart: always
    depends_on:
      - service
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_SSL_CERTIFICATE: /etc/nginx/certs/basic.pem
      NGINX_SSL_CERTIFICATE_KEY: /etc/nginx/certs/basic.key
    volumes:
      - ${APPDATA}/ASP.NET/https/basic.pem:/etc/nginx/certs/basic.pem:ro
      - ${APPDATA}/ASP.NET/https/basic.key:/etc/nginx/certs/basic.key:ro
    ports:
      - 5000:443

  service:
    image: basic-api
    build:
      context: ./src
      dockerfile: ./Basic.WebApi/Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env.docker-compose.local
    environment:
      BASEURL: https://localhost:5001
      CORS__ORIGINS: https://localhost:5000
      DATABASEDRIVER: MySQL
      CONNECTIONSTRINGS__MYSQL: Server=db;Database=basic;User=basic;Password=basic
    volumes:
      - ${APPDATA}/ASP.NET\https/basic.pfx:/src/basic.pfx:ro
    ports:
      - 5001:443

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: basic
      MYSQL_USER: basic
      MYSQL_PASSWORD: basic
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
