version: '3.7'

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/dotnet:0-7.0
    volumes:
      - ..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: basic
      MYSQL_USER: basic
      MYSQL_PASSWORD: basic

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
